baseURL = "https://rootrobotics.github.io/"
languageCode = "en-us"
title = "Root Robot AR Swift Playground"
theme = "hallo"
publishDir = ""
ignoreFiles = [ "tags", "arroot" ]
[params]
    greeting = "Root Robot AR Swift Playground"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/RootRobotics"
    [[params.links]]
        iconset = "fas"
        icon = "globe"
        title = "HomePage"
        url = "https://RootRobotics.com"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "EMail"
        url = "mailto:team@rootrobotics.com"
    [params.colors]
        background = "#3773BF"
    [params.subscribe]
        title = "Download Playground Book"
        url = "https://rootrobotics.github.io/arroot/AR-Root-Robot.playgroundbook.zip"
